version: "3.8"

services:
  strapi:
    build: .
    container_name: strapi
    restart: always
    env_file: .env
    ports:
      - "1337:1337"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_DB_PORT: ${DATABASE_PORT}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
